version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jacalloc
      POSTGRES_PASSWORD: jacalloc123

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URL: 'postgresql://jacalloc:jacalloc123@postgres:5432/jacalloc'
      PYTHONUNBUFFERED: 0
      RESOURCE_BACKEND: 'gce'

    volumes:
      - ./startup.sh:/app/startup.sh:ro
      - ./app:/app
      - ./broad-dsde-dev.json:/app/broad-dsde-dev.json:ro
      - ./broad-dsde-dev.env:/app/broad-dsde-dev.env:ro
    depends_on:
      - postgres
    links:
      - postgres:postgres
    working_dir: /app
    entrypoint: ["./startup.sh"]

  tests:
    image: broadinstitute/python-requests:2.7
    volumes:
      - ./app/test:/test
      - ./test-startup-gce.sh:/test/test-startup-gce.sh
    depends_on:
      - app
      - postgres
    links:
      - app:app
    entrypoint: bash /test/test-startup-gce.sh
