# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test-gce:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo /opt/google-cloud-sdk/bin/gcloud components update --quiet
      - run: sudo /opt/google-cloud-sdk/bin/gcloud components install beta --quiet
      - run: echo $DEV_SVC_ACCT | base64 --decode --ignore-garbage > ${HOME}/broad-dsde-dev.json
      - run: docker-compose -f inttests-gce-compose.yml up -d
      - run: sudo pip install requests
      - run: cd app/test
      - run: sudo python -m unittest apitests.TestCreateApiGcloud
      - run: sudo python -m unittest apitests.TestDependentApiGcloud
      - run: cd ~/repo
      - run: docker-compose -f inttests-gce-compose.yml stop
      - run: docker-compose -f inttests-gce-compose.yml rm -v

  test-standard:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker-compose -f inttests-compose.yml up -d
      - run: sudo pip install requests
      - run: cd app/test
      - run: sudo python -m unittest apitests.TestCreateApi
      - run: sudo python -m unittest apitests.TestDependentApi
      - run: cd ~/repo
      - run: docker-compose -f inttests-compose.yml stop
      - run: docker-compose -f inttests-compose.yml rm -v

  docker-build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build docker image
          command: docker build -t jacmrob/jacalloc .
      - run:
          name: push docker image
          command: docker push jacmrob/jacalloc

workflows:
  version: 2
  build:
    jobs:
      - test-standard
      - test-gce
      - docker-build:
          requires:
            - test-standard
            - test-gce
          filters:
            branches:
              only:
                - master
