# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test-gce:
    machine:
      docker_layer_caching: true

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $DEV_SVC_ACCT | base64 --decode --ignore-garbage > ${HOME}/broad-dsde-dev.json
      - run: docker-compose -f inttests-gce-compose.yml up -d
      - run: python -m unittest app.test.apitests.TestCreateApiGcloud
      - run: python -m unittest app.test.apitests.TestDependentApiGcloud
      - run: docker-compose -f inttests-gce-compose.yml stop
      - run: docker-compose -f inttests-gce-compose.yml rm -v

  test-standard:
    machine:
      docker_layer_caching: true
      working_directory: ~/repo
      steps:
        - checkout
        - run: docker-compose -f inttests-compose.yml up -d
        - run: python -m unittest app.test.apitests.TestCreateApi
        - run: python -m unittest app.test.apitests.TestDependentApi
        - run: docker-compose -f inttests-compose.yml stop
        - run: docker-compose -f inttests-compose.yml rm -v

  docker-build:
    machine:
      docker_layer_caching: true
      working_directory: ~/repo

      steps:
        - checkout
        - run:
            name: build docker image
            command: docker build -t jacmrob/jacalloc .
        - run:
            name: push docker image
            command: docker push jacmrob/jacalloc

workflows:
  version: 2
  build:
    jobs:
      - test
      - docker-build:
          requires:
            - test
          filter:
            branches:
              only:
                - master
